use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Result};
use clap::Args;
use serde::Serialize;

#[derive(Debug, Clone, Args)]
pub struct MemoryArgs {
    #[arg(long = "task-id", value_name = "ID", help = "Completed task id, usually from LLM/tasks/*.md")]
    pub task_id: Option<String>,

    #[arg(long, value_name = "TITLE", help = "Short title for the completed work")]
    pub title: Option<String>,

    #[arg(long, value_name = "TEXT", help = "Short completion summary")]
    pub summary: Option<String>,

    #[arg(long = "file", value_name = "PATH", help = "File touched or produced by the completed task. Repeat for multiple files.")]
    pub files: Vec<String>,

    #[arg(long = "source-task", value_name = "PATH", help = "Optional source task report under LLM/tasks/")]
    pub source_task: Option<PathBuf>,

    #[arg(long, value_name = "TEXT", help = "Optional follow-up note or unresolved issue")]
    pub follow_up: Vec<String>,

    #[arg(long, help = "Preview the memory entry without writing LLM/memory/completed_tasks.md")]
    pub dry_run: bool,

    #[arg(long, help = "Alias for --dry-run")]
    pub preview: bool,

    #[arg(long, help = "Print a machine-readable JSON memory record")]
    pub json: bool,
}

#[derive(Debug, Clone, Serialize)]
struct MemoryRecord {
    schema_version: String,
    generated_by: String,
    generated_at: String,
    dry_run: bool,
    memory_path: Option<String>,
    task_id: String,
    title: String,
    summary: String,
    files: Vec<String>,
    source_task: Option<String>,
    follow_up: Vec<String>,
}

pub fn execute(custom_kb: Option<&Path>, args: &MemoryArgs) -> Result<()> {
    let kb_path = crate::commands::init::get_kb_path(custom_kb);
    if !kb_path.exists() {
        return Err(anyhow!(
            "knowledge base path does not exist: {}. Run `kb init` first.",
            kb_path.display()
        ));
    }

    let dry_run = args.dry_run || args.preview;
    let mut record = build_record(&kb_path, args, dry_run)?;

    if !dry_run {
        let memory_path = write_memory_record(&kb_path, &record)?;
        record.memory_path = Some(relative_path_string(&kb_path, &memory_path));
    }

    if args.json {
        println!("{}", serde_json::to_string_pretty(&record)?);
    } else {
        print_record(&record);
    }

    Ok(())
}

fn build_record(kb_path: &Path, args: &MemoryArgs, dry_run: bool) -> Result<MemoryRecord> {
    let task_id = args
        .task_id
        .as_ref()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .ok_or_else(|| anyhow!("kb memory requires --task-id. Use the id from LLM/tasks/*.md."))?
        .to_string();

    let summary = args
        .summary
        .as_ref()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .ok_or_else(|| anyhow!("kb memory requires --summary. Record what was completed for future review."))?
        .to_string();

    let title = args
        .title
        .as_ref()
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .map(|s| s.to_string())
        .unwrap_or_else(|| task_id.clone());

    let source_task = args
        .source_task
        .as_ref()
        .map(|path| normalize_optional_path(kb_path, path));

    Ok(MemoryRecord {
        schema_version: "0.5.8.2".to_string(),
        generated_by: "kb-cli memory".to_string(),
        generated_at: chrono::Utc::now().to_rfc3339(),
        dry_run,
        memory_path: None,
        task_id,
        title,
        summary,
        files: args.files.clone(),
        source_task,
        follow_up: args.follow_up.clone(),
    })
}

fn write_memory_record(kb_path: &Path, record: &MemoryRecord) -> Result<PathBuf> {
    let memory_dir = kb_path.join("LLM/memory");
    fs::create_dir_all(&memory_dir)?;

    let memory_path = memory_dir.join("completed_tasks.md");
    let is_new = !memory_path.exists();
    let mut file = OpenOptions::new()
        .create(true)
        .append(true)
        .open(&memory_path)?;

    if is_new {
        writeln!(file, "# Completed Task Memory")?;
        writeln!(file)?;
        writeln!(file, "This file records completed human/LLM/agent tasks for later inspection. It is an audit memory, not a hidden execution log.")?;
        writeln!(file)?;
    }

    writeln!(file, "## {} — {}", record.generated_at, record.title)?;
    writeln!(file)?;
    writeln!(file, "- **Task ID:** `{}`", record.task_id)?;
    writeln!(file, "- **Generated by:** `{}`", record.generated_by)?;
    if let Some(source_task) = &record.source_task {
        writeln!(file, "- **Source task report:** `{}`", source_task)?;
    }
    if record.files.is_empty() {
        writeln!(file, "- **Files:** not specified")?;
    } else {
        writeln!(file, "- **Files:**")?;
        for path in &record.files {
            writeln!(file, "  - `{}`", path)?;
        }
    }
    writeln!(file)?;
    writeln!(file, "### Summary")?;
    writeln!(file)?;
    writeln!(file, "{}", record.summary)?;
    writeln!(file)?;

    if !record.follow_up.is_empty() {
        writeln!(file, "### Follow-up / unresolved issues")?;
        writeln!(file)?;
        for item in &record.follow_up {
            writeln!(file, "- {}", item)?;
        }
        writeln!(file)?;
    }

    writeln!(file, "---")?;
    writeln!(file)?;

    Ok(memory_path)
}

fn print_record(record: &MemoryRecord) {
    println!("Completed task memory record");
    println!("Task ID: {}", record.task_id);
    println!("Title: {}", record.title);
    println!("Dry run: {}", record.dry_run);
    if let Some(path) = &record.memory_path {
        println!("Memory path: {}", path);
    } else {
        println!("Memory path: LLM/memory/completed_tasks.md (not written)");
    }
    if let Some(source_task) = &record.source_task {
        println!("Source task: {}", source_task);
    }
    if !record.files.is_empty() {
        println!("Files:");
        for path in &record.files {
            println!("  - {}", path);
        }
    }
    println!("Summary: {}", record.summary);
    if !record.follow_up.is_empty() {
        println!("Follow-up:");
        for item in &record.follow_up {
            println!("  - {}", item);
        }
    }
}

fn normalize_optional_path(kb_path: &Path, path: &Path) -> String {
    if path.is_absolute() {
        relative_path_string(kb_path, path)
    } else {
        path.to_string_lossy().replace('\\', "/")
    }
}

fn relative_path_string(base: &Path, path: &Path) -> String {
    path.strip_prefix(base)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}
